apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: boatrec
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: boatrec
  template:
    metadata:
      labels:
        app: boatrec
    spec:
      containers:
      - name: boatrec
        image: mikarinneoracle/boatrec-admin-ui:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: default
      imagePullSecrets:
      - name:  oke-secret